language: c

compiler:
  - gcc

before_install:
  - sudo easy_install cpp-coveralls

script:
  - make -f Makefile.test test && make coverage

after_success:
  - coveralls --exclude t --gcov-options '\-lp'

